<?php

/*
 * Branding configs for your application
 */
return [
    'login' => [
        'page_title' => 'Sign in',
        'headline' => 'Sign in',
        'subheadline' => 'Login to your account below',
        'show_subheadline' => false,
        'email_address' => 'Email Address',
        'password' => 'Password',
        'remember_me' => 'Remember me',
        'edit' => 'Edit',
        'button' => 'Continue',
        'forget_password' => 'Forget your password?',
        'dont_have_an_account' => "Don't have an account?",
        'sign_up' => 'Sign up',
        'social_auth_authenticated_message' => 'You have been authenticated via __social_providers_list__. Please login to that network below.',
        'change_email' => 'Change Email',
        'continue_with_password' => 'Continue with password',
        'passwordless_button' => 'Continue with passwordless',
        'passwordless_sent' => 'Check your email. We sent you a one-time sign-in link.',
        'passwordless_unavailable' => 'Passwordless sign-in is unavailable for this account. Verify the email address and try again.',
        'passwordless_rate_limited' => 'Too many sign-in link requests. Please wait before trying again.',
        'passwordless_send_failed' => 'We could not send a sign-in link right now. Please try again later.',
        'couldnt_find_your_account' => 'Couldn’t find your account',
    ],
    'passwordless' => [
        'page_title' => 'Confirm passwordless sign-in',
        'headline' => 'Continue signing in',
        'subheadline' => 'Confirm below to use this one-time sign-in link.',
        'confirm_button' => 'Sign in securely',
        'cancel' => 'Return to sign in',
        'invalid_or_expired' => 'This sign-in link is invalid, expired, or has already been used.',
        'email_subject' => 'Your sign-in link',
        'email_intro' => 'Use the secure link below to sign in to your account.',
        'email_action' => 'Continue signing in',
        'email_expires' => 'This link expires in :minutes minutes and can only be used once.',
        'email_ignore' => 'If you did not request this link, you can safely ignore this email.',
    ],
    'register' => [
        'page_title' => 'Sign up',
        'headline' => 'Sign up',
        'subheadline' => 'Register for your free account below.',
        'show_subheadline' => false,
        'name' => 'Name',
        'email_address' => 'Email Address',
        'password' => 'Password',
        'password_confirmation' => 'Confirm Password',
        'already_have_an_account' => 'Already have an account?',
        'sign_in' => 'Sign in',
        'button' => 'Continue',
        'email_registration_disabled' => 'Email registration is currently disabled. Please use social login.',
    ],
    'verify' => [
        'page_title' => 'Verify Your Account',
        'headline' => 'Verify your email address',
        'subheadline' => 'Before you can proceed you must verify your email.',
        'show_subheadline' => false,
        'description' => 'Before proceeding, please check your email for a verification link. If you did not receive the email,',
        'new_request_link' => 'click here to request another',
        'new_link_sent' => 'A new link has been sent to your email address.',
        'resend_in' => 'Request again in :time',
        'resend_rate_limited' => 'Please wait before requesting another verification email.',
        'or' => 'Or',
        'logout' => 'click here to logout',
    ],
    'passwordConfirm' => [
        'page_title' => 'Confirm Your Password',
        'headline' => 'Confirm Password',
        'subheadline' => 'Be sure to confirm your password below',
        'show_subheadline' => false,
        'password' => 'Password',
        'button' => 'Confirm password',
    ],
    'passwordResetRequest' => [
        'page_title' => 'Request a Password Reset',
        'headline' => 'Reset password',
        'subheadline' => 'Enter your email below to reset your password',
        'show_subheadline' => false,
        'email' => 'Email Address',
        'button' => 'Send password reset link',
        'or' => 'or',
        'return_to_login' => 'return to login',
    ],
    'passwordReset' => [
        'page_title' => 'Reset Your Password',
        'headline' => 'Reset Password',
        'subheadline' => 'Reset your password below',
        'show_subheadline' => false,
        'email' => 'Email Address',
        'password' => 'Password',
        'password_confirm' => 'Confirm Password',
        'button' => 'Reset Password',
    ],
    'twoFactorChallenge' => [
        'page_title' => 'Two Factor Challenge',
        'headline_auth' => 'Authentication Code',
        'subheadline_auth' => 'Enter the authentication code provided by your authenticator application.',
        'show_subheadline_auth' => false,
        'headline_recovery' => 'Recovery Code',
        'subheadline_recovery' => 'Please confirm access to your account by entering one of your emergency recovery codes.',
        'show_subheadline_recovery' => false,
    ],
    'twoFactorSetup' => [
        'page_title' => 'Two Factor Authentication',
        'enabled_title' => 'You have enabled two-factor authentication.',
        'enabled_description' => "When two-factor authentication is enabled, you will be prompted for a secure, random token during authentication. You may retrieve this token from your phone's authenticator application.",
        'recovery_codes_description' => 'Store these recovery codes in a secure password manager. They can be used to recover access to your account if your two-factor authentication device is lost.',
        'regenerate_codes' => 'Regenerate Codes',
        'disable' => 'Disable 2FA',
        'disabled_title' => 'Two-factor authentication is disabled.',
        'disabled_description' => "When you enable 2FA, you will be prompted for a secure code during authentication. This code can be retrieved from your phone's Google Authenticator application.",
        'enable' => 'Enable',
        'finish_title' => 'Finish enabling two-factor authentication.',
        'finish_description' => "Enable two-factor authentication to receive a secure token from your phone's authenticator during login.",
        'finish_instructions' => "Scan the QR code or enter the setup key using your phone's authenticator app, then provide the one-time code.",
        'setup_key' => 'Setup Key',
        'code' => 'Code',
        'invalid_code' => 'Invalid authentication code. Please try again.',
        'cancel' => 'Cancel',
        'confirm' => 'Confirm',
    ],

];
